In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!sudo apt-get update
!apt-get install make autoconf automake libtool pkg-config gcc libsonic-dev libpcaudio-dev
!git clone https://github.com/espeak-ng/espeak-ng.git
!cd espeak-ng && ./autogen.sh && ./configure --with-extdict-cmn && make && make install && ldconfig

!pip install phonemizer
!pip install opencc

Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:6 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:9 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:14 http://security.ubuntu.com/ubuntu 

In [3]:
#!pip install torchdata

In [4]:
#!pip install -U torchtext

In [3]:
import os
import json
import requests
from time import time
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

# Evaluation

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [4]:
from sqlalchemy import create_engine

In [5]:
import torchtext

In [6]:
import torch
from torch import nn
from torch.nn import functional as F
from torch.optim.optimizer import Optimizer
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset
from torch.utils.data.dataset import random_split
from torch.utils.mobile_optimizer import optimize_for_mobile
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence


from torchtext.data.utils import get_tokenizer
from torchtext.data.functional import to_map_style_dataset
from torchtext.vocab import build_vocab_from_iterator

In [7]:
from phonemizer import phonemize
from phonemizer.backend import EspeakBackend
from phonemizer.separator import Separator

In [8]:
from tqdm import tqdm
from sklearn.metrics import accuracy_score
import gc

In [9]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.5 MB 5.1 MB/s 
     |████████████████████████████████| 163 kB 48.6 MB/s 
     |████████████████████████████████| 7.6 MB 46.0 MB/s 


In [10]:
from transformers import AutoTokenizer

In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [12]:
engine = create_engine("postgresql://postgres:EQ6TfGSxLf7kef4bET31@containers-us-west-69.railway.app:7857/railway")
data_df = pd.read_sql_table('TrainingData_MenuItemPressed', engine)
data_df = data_df[['transcription', 'menuItemId', 'createdAt']]
data_df = data_df.rename(columns={"transcription": "text", "menuItemId": "label"})
data_df = data_df.sample(frac=1).reset_index(drop=True)
assert "text" in data_df.columns
assert "label" in data_df.columns
data_df.head()

text                                 label  \
0                        Fountain  03a91748-92e2-4c3f-9b4c-683f4de4cbbf   
1                                  3742894d-e51b-4d25-8553-3179480bb616   
2  California burgers and chicken  c4d3a7c6-11e5-4435-a796-955bcce36d81   
3               Belgian Moon with  4b8fc815-f396-440f-b450-4445b8bb9b57   
4                    Caesar salad  4c20d50b-c570-44af-ab74-2ea77d770f8b   

                createdAt  
0 2022-11-08 19:27:37.985  
1 2022-11-09 21:16:19.347  
2 2022-11-08 19:04:56.259  
3 2022-11-07 02:10:31.731  
4 2022-11-04 02:31:34.381

In [13]:
data_df.shape

(8997, 3)

In [14]:
data_df = data_df.loc[data_df.createdAt < "Nov 1 2022"]

In [15]:
data_df.shape

(1316, 3)

In [16]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [17]:
space_separator = Separator(phone=',', syllable='', word=' ')
tokenizer = EspeakBackend('en-us')

phonemes = tokenizer.phonemize(["a span of text what is causing the word mismatch?"], space_separator, strip=True)
phonemes = ' '.join(phonemes).strip().split(' ')
extended_phonemes = []
for x in phonemes:
  extended_phonemes += x.split(',')

extended_phonemes

['ɐ',
 's',
 'p',
 'æ',
 'n',
 'ʌ',
 'v',
 't',
 'ɛ',
 'k',
 's',
 't',
 'w',
 'ʌ',
 't',
 'ɪ',
 'z',
 'k',
 'ɔː',
 'z',
 'ɪ',
 'ŋ',
 'ð',
 'ə',
 'w',
 'ɜː',
 'd',
 'm',
 'ɪ',
 's',
 'm',
 'æ',
 'tʃ']

In [18]:
labels_set = set(data_df["label"].values)

In [19]:
def get_menu(menu_id):
  """
    gets a woflow menu json
  """

  header={"x-impersonated-user-id":"yolo", "x-api-key":"yolo"}
  response = requests.get(f"https://staging-api.origamigigs.com/restaurants/{menu_id}", headers=header)
  menu = response.json()
  return menu


def get_menu_items(menu:json):
  """
    returns a dictionary where menuItemId as the key,
    holding a dictionary of the menu item name, and the word tokens within it
  """
  menu_items_cleaned = dict()
  menu_items = menu['restaurant']['menu']['items']
  for item in menu_items:

    name = item.get('name')

    phonemes = tokenizer.phonemize([name], separator=space_separator, strip=True)
    phonemes = ' '.join(phonemes).strip().split(' ')
    extended_phonemes = []
    for x in phonemes:
      extended_phonemes += x.split(',')

    menu_items_cleaned[item.get('id')] = {
        'name': name,
        'tokens': extended_phonemes
    }

  return menu_items, menu_items_cleaned

def build_menu(menu_items_list:list):
  """
  """
  menu = dict()
  for item in menu_items_list:
    menu[item.get('id')] = {
        'name': item.get('name'),
        'category': item.get('category').get('name')}

  return menu

menu_items, menu_items_extended = get_menu_items(get_menu('8e7ab578-fda1-4a0a-85e2-0372b35a8713'))
menu = build_menu(menu_items)
all_items = set(menu_items_extended.keys())
menu_items_extended

{'ebb77efa-ce69-489c-a934-c959b90047e1': {'name': 'Albator',
  'tokens': ['æ', 'l', 'b', 'eɪ', 'ɾ', 'ɚ']},
 'a99d16ef-9cd6-4214-8444-79f9828161bc': {'name': 'Kickflip',
  'tokens': ['k', 'ɪ', 'k', 'f', 'l', 'ɪ', 'p']},
 'e225a1bc-d574-45f2-94fd-b735f058c63e': {'name': 'Poison',
  'tokens': ['p', 'ɔɪ', 'z', 'ə', 'n']},
 'ca4b7aad-d85b-406c-8fec-cfb9e731bab9': {'name': 'Mojito',
  'tokens': ['m', 'oʊ', 'h', 'iː', 'ɾ', 'oʊ']},
 '5d5e6d5b-b6ac-4d69-a7cd-ed6d02cfde3e': {'name': 'La Boite À Gogo',
  'tokens': ['l', 'æ', 'b', 'ɔɪ', 't', 'æ', 'ɡ', 'oʊ', 'ɡ', 'oʊ']},
 '5f122701-8e65-4b52-84f9-d03fffe0cae0': {'name': 'Reggae',
  'tokens': ['ɹ', 'ɛ', 'ɡ', 'iː']},
 '9d0fc04e-bc4b-4fe5-95b4-ac7698bb4b3f': {'name': 'John Lemon',
  'tokens': ['dʒ', 'ɑː', 'n', 'l', 'ɛ', 'm', 'ə', 'n']},
 '169e0414-63ae-4c16-83b7-83f1638fd8c4': {'name': 'Tic Toc',
  'tokens': ['t', 'ɪ', 'k', 't', 'ɑː', 'k']},
 '57d269b3-d2fd-43be-9773-f2c4c3486fff': {'name': 'Paix',
  'tokens': ['p', 'eɪ', 'k', 's']},
 '9283cf36-5982-4

In [20]:
id2label = {}
idx = 0
for label in labels_set:
  if label in all_items:
    id2label[label] = idx
    idx +=1 

label2id = {}
for key, value in id2label.items():
  label2id[value] = key

label2name = dict()
for key, value in id2label.items():
  label2name[value] = menu[key].get('name')

def uuid2label(menu_item_id):
  if menu_item_id in all_items:
    return id2label[menu_item_id]
  else: return 0

data_df['label'] = data_df['label'].apply(uuid2label)

In [21]:
### Drop zero'd label Data
data_df = data_df[data_df.label != 0]

### Drop Rows with NaN data
data_df = data_df.dropna()

data_df.shape

(1307, 3)

In [22]:
max_len = 0 
total_length = 0
counter = 0
for name, inner_dict in menu_items_extended.items():
  counter+=1
  length_of_tokens = len(inner_dict.get('tokens'))
  total_length += length_of_tokens
  if length_of_tokens > max_len:
    max_len = length_of_tokens

In [23]:
average_length = total_length / counter
average_length

11.445229681978798

In [24]:
class OrigamiDataset(Dataset):

  def __init__(self, data_df):
    self.X = data_df['text'].values
    self.y = data_df['label'].values
        
  def __len__(self):
    return len(self.y)

  def __getitem__(self, idx):
    return self.y[idx], self.X[idx]

In [25]:
def yield_tokens(data_iter):
  """
      tokenizes text
  """
  for _, text in data_iter:
    phonemes = tokenizer.phonemize([text], space_separator, strip=True)
    #phonemes = phonemes[0].split(' ')
    phonemes = ' '.join(phonemes).strip().split(' ')
    extended_phonemes = []
    for x in phonemes:
      extended_phonemes += x.split(',')
    yield extended_phonemes

def text_pipeline(text:str):
  """
      converts a string to a 
      list of word tokens by passing the string
      through a tokenizer and the word to index dictionary
  """
  phonemes = tokenizer.phonemize([text], space_separator, strip=True)
  #phonemes = phonemes[0].split(' ')
  phonemes = ' '.join(phonemes).strip().split(' ')
  extended_phonemes = []
  for x in phonemes:
    extended_phonemes += x.split(',')

  return vocab(extended_phonemes)


In [ ]:
train_size = .80
train_iter, test_iter = OrigamiDataset(data_df[:int(data_df.shape[0]*train_size)]), OrigamiDataset(data_df[int(data_df.shape[0]*train_size):])
vocab = build_vocab_from_iterator(yield_tokens(train_iter), specials=["<unk>"])
vocab.set_default_index(vocab["<unk>"])

In [27]:
len(vocab)

59

In [28]:
data_df.head()

text  label  \
15  Like to replicate this it'll be here but then ...     52   
16                                    Big Jack burger     74   
22                                            Blanche    153   
23                                     Crispy chicken    276   
24                             Large Jamison iced tea     28   

                 createdAt  
15 2022-10-29 20:21:17.255  
16 2022-10-19 02:11:45.985  
22 2022-10-31 18:14:50.921  
23 2022-10-28 21:07:10.338  
24 2022-10-28 19:54:50.582

In [136]:
max_sequence = 40
BATCH_SIZE = 8
embed_len = 768
hidden_dim = 512
n_layers=1
num_classes=len(all_items)
learning_rate = 0.001
epochs = 100

In [137]:


def collate_batch(batch):
  """
      top level collate_fn
  """
  y, x = list(zip(*batch))

  text_list = []
  for _, text in zip(y, x):
    phoneme_text = text_pipeline(text)
    text_list.append(phoneme_text)

  padded_text_list = [torch.tensor(phonemes+([0]* (max_sequence-len(phonemes))), dtype=torch.int64) if len(phonemes)<max_sequence else torch.tensor(phonemes[:max_sequence], dtype=torch.int64) for phonemes in text_list]
  
  label_list = torch.tensor(y, dtype=torch.int64)
  batch_text_list = torch.stack(padded_text_list)
 
  return batch_text_list.to(device), label_list.to(device)

In [138]:
num_train = int(len(train_iter) * 0.95)

split_train_, split_valid_ = random_split(
    train_iter, 
    [num_train, len(train_iter) - num_train]
)

train_dataloader = DataLoader(split_train_, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_batch)
valid_dataloader = DataLoader(split_valid_, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_batch)
test_dataloader = DataLoader(test_iter, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_batch)

for x, y in train_dataloader:
  print(x.shape, y.shape)
  #print(x, y)
  break

torch.Size([8, 40]) torch.Size([8])


In [139]:
device

device(type='cpu')

In [140]:
batch_1 = next(iter(train_dataloader))

In [141]:
#batch_1[0]

In [142]:
class LSTMClassifier(nn.Module):

    def __init__(self):

        super(LSTMClassifier, self).__init__()

        self.embedding_layer = nn.Embedding(
            num_embeddings=len(vocab), 
            embedding_dim=embed_len
          )
        
        self.lstm = nn.LSTM(
            input_size=embed_len, 
            hidden_size=hidden_dim, 
            num_layers=n_layers, 
            batch_first=True
        )
        
        self.linear = nn.Linear(hidden_dim, num_classes)


    def forward(self, X_batch):

        embeddings = self.embedding_layer(X_batch)
        
        hidden = torch.zeros(n_layers, len(X_batch), hidden_dim).to(device) 
        carry = torch.zeros(n_layers, len(X_batch), hidden_dim).to(device)

        output, (hidden, carry) = self.lstm(embeddings, (hidden, carry))


        return self.linear(output[:,-1])

In [1]:
BEST_MODEL_ACCURACY = 0

def CalcValLossAndAccuracy(model, loss_fn, val_loader):
    global BEST_MODEL_ACCURACY

    with torch.no_grad():
        Y_shuffled, Y_preds, losses = [],[],[]
        for X, Y in val_loader:
            preds = model(X)
            loss = loss_fn(preds, Y)
            losses.append(loss.item())

            Y_shuffled.append(Y)
            Y_preds.append(preds.argmax(dim=-1))

        Y_shuffled = torch.cat(Y_shuffled)
        Y_preds = torch.cat(Y_preds)

        print("Valid Loss : {:.3f}".format(torch.tensor(losses).mean().to(device)))
        valid_accuracy = accuracy_score(Y_shuffled.cpu().numpy(), Y_preds.cpu().numpy())
        print("Valid Acc  : {:.3f}".format(valid_accuracy))
        if valid_accuracy > BEST_MODEL_ACCURACY:
          print("!!!             NEW BEST MODEL                    !!!")
          BEST_MODEL_ACCURACY = valid_accuracy
          path_to_data = f"{os.getcwd()}/drive/MyDrive/origami_data/"
          torch.save(model.state_dict(), f'{path_to_data}ph_lstm_origami.pt')
        

def TrainModel(model, loss_fn, optimizer, train_loader, val_loader, epochs=10):


    for i in range(1, epochs+1):
        losses = []
        for X, Y in tqdm(train_loader):


            Y_preds = model(X) ## Make Predictions

            loss = loss_fn(Y_preds, Y) ## Calculate Loss
            losses.append(loss.item())
            optimizer.zero_grad() ## Clear previously calculated gradients
            loss.backward() ## Calculates Gradients
            optimizer.step() ## Update network weights.
        print(f"Epoch : {i}")
        print("Train Loss : {:.3f}".format(torch.tensor(losses).mean()))
        CalcValLossAndAccuracy(model, loss_fn, val_loader)

In [2]:
lstm_classifier = LSTMClassifier().to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = Adam(lstm_classifier.parameters(), lr=learning_rate)

TrainModel(lstm_classifier, loss_fn, optimizer, train_dataloader, valid_dataloader, epochs)

NameError: name 'LSTMClassifier' is not defined

In [145]:
BEST_MODEL_ACCURACY

0.9056603773584906

In [146]:
best_model = LSTMClassifier()

In [147]:
path_to_data = f"{os.getcwd()}/drive/MyDrive/origami_data/"

In [148]:
best_model.load_state_dict(
    torch.load(f"{path_to_data}ph_lstm_origami.pt")
)

best_model.eval()

LSTMClassifier(
  (embedding_layer): Embedding(59, 768)
  (lstm): LSTM(768, 512, batch_first=True)
  (linear): Linear(in_features=512, out_features=283, bias=True)
)

In [149]:
best_model.to(device)

LSTMClassifier(
  (embedding_layer): Embedding(59, 768)
  (lstm): LSTM(768, 512, batch_first=True)
  (linear): Linear(in_features=512, out_features=283, bias=True)
)

In [150]:
def MakePredictions(model, loader):
    Y_shuffled, Y_preds = [], []
    for X, Y in loader:
        preds = model(X)
        Y_preds.append(preds)
        Y_shuffled.append(Y)
    
    gc.collect()
    Y_preds, Y_shuffled = torch.cat(Y_preds), torch.cat(Y_shuffled)

    return Y_shuffled.cpu().numpy(), F.softmax(Y_preds, dim=-1).argmax(dim=-1).cpu().numpy()

Y_actual, Y_preds = MakePredictions(best_model, test_dataloader)

In [151]:

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Test Accuracy : {}".format(accuracy_score(Y_actual, Y_preds)))
print("\nClassification Report : ")
print("\nConfusion Matrix : ")
print(confusion_matrix(Y_actual, Y_preds))

Test Accuracy : 0.732824427480916

Classification Report : 

Confusion Matrix : 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]


In [153]:
torch.save(vocab, f"{path_to_data}phoneme_vocab.pth", )
